# Generated by Django 5.1 on 2024-08-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foreign_Key', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Foreign_Key.employee'),
        ),
    ]
