# Generated by Django 5.1 on 2024-08-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foreign_Key', '0002_alter_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Foreign_Key.department'),
        ),
    ]
