# Generated by Django 5.0.7 on 2024-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_instructor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=200, unique=True)),
                ('instructor_name', models.CharField(max_length=200)),
                ('instructor_age', models.IntegerField()),
                ('instructor_email', models.EmailField(max_length=200, unique=True)),
                ('instructor_courses', models.CharField(max_length=200)),
                ('employment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=200, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_age', models.IntegerField()),
                ('student_email', models.EmailField(max_length=200, unique=True)),
                ('student_courses', models.CharField(max_length=200)),
                ('enrolled_date', models.DateField()),
            ],
        ),
    ]
