# Generated by Django 5.0.7 on 2024-08-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Instructors',
            new_name='Instructor',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
